name: food_dash
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/burger.jpg
    - lib/assets/images/burger combo+ drinks.jpg
    - lib/assets/images/posho+fish.jpg
    - lib/assets/images/vegetable chicken.jpg
    - lib/assets/images/vegetable noodles.jpg
    - lib/assets/images/snacks.jpg
    - lib/assets/images/youghut.jfif
    - lib/assets/images/rolex.jfif
    - lib/assets/images/paste gnuts.jfif
    - lib/assets/images/pilau beef lusania.jpg
    - lib/assets/images/chips+fish.jfif
    - lib/assets/images/casava chips.jpg
    - lib/assets/images/pineapple juice.jfif
    - lib/assets/images/sausagevip.jpg
    - lib/assets/images/pizza combo.jpg
    - lib/assets/images/pilau+fish.jpg
    - lib/assets/images/chicken favourite.jpg
    - lib/assets/images/chips chicken salads.jfif
    - lib/assets/images/chapati.jfif
    - android/app/src/main/res/mipmap-hdpi/foodddassh.png
    - ios/Runner/Assets.xcassets/AppIcon.appiconset/_/120.png
    - android/app/src/main/res/mipmap-hdpi/foodddassh.png
    - android/app/src/main/res/mipmap-mdpi/foodddassh.png
    - android/app/src/main/res/mipmap-xhdpi/foodddassh.png
    - android/app/src/main/res/mipmap-xxxhdpi/foodddassh.png
    - lib/assets/images/all favourites ice cream.jfif


